# This is a basic workflow to help you get started with Actions

name: Scraper

on:
  push: 
    branches: main
  schedule:
  - cron: "0 0 1 * *"
    branches: main


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Scraper:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.REPO_TOKEN }}

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
         python-version: "3.8"

    - name: Install Python dependencies and run the code
      run: |
            cd Scraper
            pip install -r requirements.txt
            python scraper.py
  
    - name: Commit data files
      run: |
          pwd
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git add -A
          git commit -a -m "Added new date for Scraper" || echo "Nothing to commit"
    - name: Install Python dependencies and run the code2
      run: |
            cd Scraper
            pip install -r requirements.txt
            python limpieza.py
  
    - name: Commit data files
      run: |
          pwd
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git add -A
          git commit -a -m "Added new date for Scraper" || echo "Nothing to commit"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
